version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "S1038: should use fmt.Fprintf instead of fmt.Fprint"
      - linters:
          - staticcheck
        text: "SA1019: (x509.EncryptPEMBlock|strings.Title)"
      - linters:
          - staticcheck
        text: "ST1005: error strings should not be capitalized"
      - linters:
          - staticcheck
        text: "ST1005: error strings should not end with punctuation or newlines"
      - path: (.+)\.go$
        text: SA1006
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
